name: purple_theme
description: A simple theme manager for Flutter apps.
version: 0.1.0
homepage: www.purplesoft.io

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
